---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: inventory-service-secrets-nest
  namespace: examples
spec:
  encryptedData:
    DATABASE_PASSWORD: AgCr3QjCGA2r6lKQVe9dqH/h+LcvKSPaezVDRM3Wom/3KBJP99uXhiGHWSxHzNgW+DqaWtVLhHZ1SZ1GBCpJOeBGKjoEKUc8flUAE+d1VNEJfTQ0W/vKxgJMRbncLnDZpVSnZDWS1UAkSr9vlxkkFzs6siJJI6iD+wXJdBHDIlFCOoW53eppCFIr6fXvjVUlOp6m0viLt7eZmaUKwa35s1cNK1ZKGDGhzMdR8OA4+U5pziZK2Z2Ej4x/pvAYGQUuhI5AgA6nu1VSkeE6OKnuUtSEvbVOwGPVJxQ16jtFHljwfCbkr9ygR6yFkZpurGsprxUGyojQzXfoSsK9joH0kc9l+HQFTCFIJdBf6Ng/yIt0KHsYGO9beV9bDYGL0Wm8JjTC4IlpV/fLILmr6PCrSPXy+cY9nPlNzb0ipVtPZWRTM52eYxUXpir7EJGD2TROeqCBEsVu5FhJS8R8+m6QrsBej3Grp4dFIvexLfTIR99d9JiDKKEws1xYIHTQCy/hUC8PyxfgEinmVvdvCdAfXQGc4A6XlE5JI/Flp/pDsynBEVEsneWWR/vXNu7ZQisuFrKhFF19I2WZBWWIbDjY6jqSFHtw0pZR9vbwt+41jkDcj6WfPgUkPzfcIiuZqPuk56nrY4usAycsq9hMUH7gektd503o7e0Z2A5qTMZP7MPPmsJPNn0duxEEKgmCQomTtyBPbwg0Syw=
    DATABASE_USER: AgA94Yy4E+NJDCMcBK3rVRk+SEB5n7xEGBb+mxhZumzCPRLFxthSq62hQ9SOv1RKtFd4FgsMJY7EVXVnIDrCzZnnDz3UPHhsV7xGOa2xrYMbgFpYhgZNSYnTxsKpeAZanHn87X+MLsQisnJn6A8dBJbumFRRmYp2B1Ftw21uLDUAe1VOjNon/YkU27gRxcGiIeCLDqm7Kc6tJJiYcqYjBgVAZM5qbx6SqAiFBQjb8e+wIqIeqWoCKGkuo1ea15stLf/00jgZKwpwT3mx10un376tizhG7rwJW7CNSJ4IZ0M/urNyj5xdiaTdylG50cj56F3WWfbKe0r0suMcQq5MbPpkupoiUpUmUXEuVqSo5vH7mjaRQFxfUpkkqe6OMWpWdYusXXAmIKIEbxhcWGguZ4eCevZN3C0Nx18uBkT9HA4Q4gj1imLAxyy1CzVGt4ch51FjMM0CLB4xslh9T+lLtB8MgTroz7yevwLrwGrg+JXvZHAMybhMrIRjz/rlD1TaHPe7NV1R5LxJvRn8fQOIi2GR8mnRz2/6ZJ2dL3PiK1LGAZzwSN6aWeOIPdNPUp/gQVx6DrhtLip86cDuotSsbyabTZloFofZrgefriabzBQohfSz3Q3KFVKf+8I7piVp4Ab/8vNKt3Sf5jbqvDhT24QZuIc0VDq/DEvXV8+PuE6fSQWofY3RpyjJVGQYFIzhkb/2BwPq8+RT8ds=
  template:
    metadata:
      creationTimestamp: null
      name: inventory-service-secrets-nest
      namespace: examples
    type: Opaque
