---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: inventory-service-secrets
  namespace: examples
spec:
  encryptedData:
    DATABASE_PASSWORD: AgC8MKhErL3LQTTYYkxKvCjyL0bu80ytfJWopuzr/z/GlroP/KSCW275qBniVxQuVnEzvbUdcD2Zg/7U/ou+Sj/emYDsFoX4/ReuMbTpQBwRT4Af4m4h5asAEdCxEuDbvk2UtuYWg6YWNKpYtbLONimZ24jqFPXuLvPRS9w9KP5hPrh/xa0NvE4zU1U3YTuCSRv+PqydBiFjP+KaMxHxAI2tNv6vVjNpCkrDM0ZJEoywekrHLytYoOqyNhtocQeB768HtN0tGuOzpoENt6yVjQ+iJfFLykcmkB4tK4ULm0lQAinbbFHiEQNoUbMVFBuxI0X6ABNCJQas2jBEOgf4qI4aw5NJZkxe4SISYQqI1XR8D6i+TSuu0txaLxSe/vxxsFmRBbNW5xqGwIrZrNrr/VtT8sXctX4CvveRfZl+oFkNasHq1/r84Bjnxjx3OXZ0C3Gw1vQJeumaWFZoI7AJYXRBOcpPeb3n14W9kHx6wcZmITNpn9P/EO509FeATaZUsCtu5GSnkTPr9FhjRD4TvEwUPzQPTFi6b+5ioHpDq1RCjdIv3sW1o25kGGD+hzWT0PsHeq/5Nag2K0Pr4ncJcosN/ca2BdEVnnaCVnFl2qj7ZaC0VOSv2uvVJdx1xw8cgM+kNG+tMxLTQF96vaCAoVIQMHCl5lFpUag+4t6ZFNwaPq1SXIcxmAfcZyFuc620hUnHUri1Yvo=
    DATABASE_USER: AgBcWGkvirZGr8VG3eC4ncyrWkl3e6NaHww9znFgi31rVbdUlS6EaUKHWbl4KDmgno9iocYkBhew6lex0LOIK7ZbUkKHlCMuHPHvpmDNmXAgfWy0GjeFVIwyP0QMvpxb/towydfNAVOj0nQtCKp8cA1zdy17HI2ma2dyG67jlzc8b16lmil2aK2lsg/AwZYOblIBBE6nYavXCNbkbi64ZACdh7FSDrz8Rse6Mv31oMf0IORfLSJ9rZvRWZ9JmrQW2QXd/nH3vGYsE4bZ2DOeqXAYxsITYCe9l0wGJt+aG/Kj0C0q+Xw0+Hx7AFM7OfLd1h3jewMT7t7CEukxE63wVe3QWxdDbX/eBLlUFoJJ0DIulOXUf9962S9L2JDe2KNmDyaBCX0DfFqxDEbtHA4lRQbkaRUv4E4Wzy6C7dnsbrznPVi/4szFXHcp+3HOk0u4/B2b/QOArSe2W73DtQ71qFH5AET7O4VEtSzjExwwh0PoZtY+fkM+AbT5KtZ4irb67xU8z8GijEYmJNm9AuaLKeFgxd4cwxSKak2rKKKjrLf27hVGF0FvEI+2BZiU7jsKlS0Fdhc2s2kwBUC8YkwmxI+z7PqVzDEFbUDHD7j6NtfXtxQiE3EyUS7lvo+9dsF0NYtDJGuI2UzryWre2qeNm14lgERd+R7Qxh9e5LEuiPtXxLwQ7Bb3YkRSRImSNGprHcWcNfv3pG+WSIg=
  template:
    metadata:
      creationTimestamp: null
      name: inventory-service-secrets
      namespace: examples
    type: Opaque
