apiVersion: v1
kind: Service
metadata:
  name: inventory-service-nest
  labels:
    app: inventory-service-nest
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: inventory-service-nest
